### ISSUE TITLE
operator .^ not defined

### ISSUE THREAD

**Issue by bal-agates** [AlexanderTar/LASwift#16]
CAUTION.  This is an obvious problem and others apparently do not have it so it might be due to something in my environment or something I have done wrong.

When I try compile I get the error

`./MatrixExponent.swift:39:13: Operator implementation without matching operator declaration`

In ./Operators.swift I do not see a definition for ".^" nor have I found one elsewhere.  I solved my problem by making the following changes in ./Operators.swift

```
diff --git a/LASwift/Operators.swift b/LASwift/Operators.swift
index 71630e2..34cf140 100755
--- a/LASwift/Operators.swift
+++ b/LASwift/Operators.swift
@@ -6,6 +6,13 @@
 // This software may be modified and distributed under the terms
 // of the BSD license. See the LICENSE file for details.
 
+precedencegroup ExponentiationPrecedence {
+    associativity: right
+    higherThan: MultiplicationPrecedence
+}
+
+infix operator .^ : ExponentiationPrecedence
+
 infix operator .* : MultiplicationPrecedence
 infix operator ./ : MultiplicationPrecedence
 infix operator ./. : MultiplicationPrecedence
```

I am using macOS 10.13.6, Xcode 10.1 with Swift 4.2.  Yes I know it is a little old but my Power Mac doesn't support newer macOS.  I am building for a macOS (x86_64) command line app.  Because I didn't want to deal with the pods and test cases I have copied the sources into my own new Xcode project.  Once I made this change it compiled and seemed to work well.  I really like LASwift.

Why am I seeing this and no one else?  Did I loose something by creating a new project?  Do other versions of Swift either have the operator defined, have a default, or don't care?

**Comment by bal-agates** [comment]
In [Apple Developer Doc - stdlib operators declarations](https://developer.apple.com/documentation/swift/swift_standard_library/operator_declarations) I did not find the ".^" operator defined.  However, in Xcode 12.0.1 (Swift 5.3) I see the operator ".^" defined in 

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/swift/Swift.swiftmodule/x86_64.swiftinterface` 

I traced this down to the stdlib source file [swift/stdlib/public/core/SIMDVector.swift](https://github.com/apple/swift/blob/9af806e8fd93df3499b1811deae7729176879cb0/stdlib/public/core/SIMDVector.swift).  The ".^" operator was added about 2 years ago after Swift 4.2 and I think starting in Swift 5.0.  

I did not research if the stdlib operator precedence for ".^" makes sense for LASwift.  I created a pull request that includes a change where I added a guard around an LASwift declaration of operator ".^" so this will compile with both Swift 4.2 and Swift 5.x (I only tested with Swift 5.3).

**Comment by AlexanderTar** [comment]
Looks like you've fixed it in your PR. Thank you
