### ISSUE TITLE
Suggested enhancements zeros(), ones(), .T, hstack(), vstack()

### ISSUE THREAD

**Issue by bal-agates** [AlexanderTar/LASwift#17]
Suggesting enhancement to Matrix.swift.  All changes are modeled after NumPy functionality but adapted to Swift.  Added zeros(like:), ones(like:), .T for transpose, hstack() and vstack().  I haven't been able to get the LASwift Xcode project completely working on my system so I do not feel comfortable changing GitHub sources myself.

Someone should probably review where I implemented ".T".  I debated if it would be better to put in an extension but decided it would be better to put the property in the main Matrix class.

The Pods and test cases is one area I am having problems with on my system so I have not provided test cases although I have tested my implementations with print statements and manually verified.

Enclosed updated Matrix.swift and differences (diff -u) Matrix.swift.diff.
[Matrix.swift.diff.zip](https://github.com/AlexanderTar/LASwift/files/5215871/Matrix.swift.diff.zip)
[Matrix.swift.zip](https://github.com/AlexanderTar/LASwift/files/5215868/Matrix.swift.zip)

**Comment by AlexanderTar** [comment]
Hi. Thank you for the contribution. Would you mind creating a PR with your changes so I can review it and merge?

**Comment by AlexanderTar** [comment]
Sorry for taking so long. The PR has been merged
