### ISSUE TITLE
Suggested enhancement lstsq (least square)

### ISSUE THREAD

**Issue by bal-agates** [AlexanderTar/LASwift#18]
I created a func lstsq() for LASwift to compute the least squares solution to an overdetermined linear system A*X=B.  This is roughly equivalent to the NumPy function with the same name.  My implementation uses Accelerate framework LAPACK dgels().  I put lstsq() in a new file MatrixLeastSquare.swift but it could probably put in MatrixAlgebra.swift since it is similar to svd().  I felt more comfortable having it in its own file so I could be more verbose with comments.  Note that this implementation depends on a transpose shortcut (.T) that I submitted in a separate enhancement suggestion.

Enclosed are the sources MatrixLeastSquare.swift, lstsq_test.swift (a documented test case) and numpy_lstsq_example3.py (roughly equivalent to lstsq_test.swift for verification).

[MatrixLeastSquare.swift.zip](https://github.com/AlexanderTar/LASwift/files/5215970/MatrixLeastSquare.swift.zip)
[lstsq_test.swift.zip](https://github.com/AlexanderTar/LASwift/files/5215973/lstsq_test.swift.zip)
[numpy_lstsq_example3.py.zip](https://github.com/AlexanderTar/LASwift/files/5215995/numpy_lstsq_example3.py.zip)

**Comment by AlexanderTar** [comment]
Would you mind creating a PR with your changes so I can review it and merge?

**Comment by bal-agates** [comment]
There should already be a pull request unless I have messed something up.  My first time creating a GitHub fork and pull request.

I did make one additional commit after initially submitting my pull request.  I can see that change in the pull request so hopefully you can also.

-brett

**Comment by AlexanderTar** [comment]
Sorry for taking so long. The PR has been merged
