### ISSUE TITLE
Add a matrix determinant function

### ISSUE THREAD

**Issue by naccib** [AlexanderTar/LASwift#20]
Currently I'm calculating determinants by multiplying all eigenvalues returned from the `eig` function. However, this method is imprecise for some matrices, specially rather large ones.

A more robust and idiomatic way to calculate the matrix determinants would be by calling LAPACK's [dgetrf](http://www.netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational_ga0019443faea08275ca60a734d0593e60.html) function, which performs LU factorisation, which can be utilised to compute the determinant [as such](https://s-mat-pcs.oulu.fi/~mpa/matreng/eem3_4-3.htm).

**Comment by AlexanderTar** [comment]
I have added determinant calculation. It will be part of 0.2.5
