### ISSUE TITLE
Update Quick and Nimble in Package.swift

### ISSUE THREAD

**Issue by raphimulator** [AlexanderTar/LASwift#24]
The current versions of Nimble and Quick do not match between the `Example/Podfile` and `Package.swift`.
Can you please update the version in the Swift Package as well? 

It causes dependency version conflicts in my project and Swift Package Manager is very unforgiving, when it comes to that.

**Comment by stuffmc** [comment]
Bump. Anything new, @AlexanderTar? Thanks.

**Comment by AlexanderTar** [comment]
Updated `Nimble` and `Quick` version across the repo
