### ISSUE TITLE
Eigenvalues and eigenvector of matrix is wrong

### ISSUE THREAD

**Issue by Arman1997** [AlexanderTar/LASwift#6]
I have tried to count eigenvalues and eigenvectors of this simple matrix
<img width="246" alt="screen shot 2017-09-19 at 3 13 04 pm" src="https://user-images.githubusercontent.com/20797432/30589825-110f091c-9d4d-11e7-80b2-8a52d9b63b4b.png">
after that i noticed that both values and vectors are wrong 
<img width="403" alt="screen shot 2017-09-19 at 3 20 38 pm" src="https://user-images.githubusercontent.com/20797432/30590066-1ed5957e-9d4e-11e7-84e9-52df5002fac2.png">
you can check it in this article 
[http://lpsa.swarthmore.edu/MtrxVibe/EigMat/MatrixEigen.html](url) 

i have tried to count that by my own and same result as with mathlab
you are using dsyevd_ function but i tried with dgeev_ and its work great

<img width="626" alt="screen shot 2017-09-19 at 3 17 23 pm" src="https://user-images.githubusercontent.com/20797432/30589991-d5f8a058-9d4d-11e7-9433-fdd298ae70b4.png">

any ideas?

**Comment by Arman1997** [comment]
same issue for normilize(Vector)
<img width="188" alt="screen shot 2017-09-19 at 6 07 19 pm" src="https://user-images.githubusercontent.com/20797432/30596541-6f9a65b8-9d65-11e7-81e8-146da5105479.png">

<img width="345" alt="screen shot 2017-09-19 at 6 08 34 pm" src="https://user-images.githubusercontent.com/20797432/30596606-a48ca0e2-9d65-11e7-814f-f540dfe72143.png">

but it should be [0.802,0.267,0.534]

**Comment by AlexanderTar** [comment]
I guess there was a bit of misunderstanding regarding `normalize` function. It actually does not do what you think it does. The function deducts mean value from vector elements and divides it by their standard deviation. This method is widely used for various ML application. In this case the name may be misleading.

As for eigen vectors, I'll try to debug and will probably use `dgeev_` as you suggested

**Comment by AlexanderTar** [comment]
I have updated `eig` function to use `dgeev_ `, please check.

**Comment by Arman1997** [comment]
everything works
