### ISSUE TITLE
error in inv(_ A: Matrix) after migrating to swift 4

### ISSUE THREAD

**Issue by Arman1997** [AlexanderTar/LASwift#7]
after migrating to swift 4 and changing build settings to recommended, occurred an error in inv(_ A: Matrix)
<img width="1397" alt="screen shot 2017-12-06 at 2 40 30 am" src="https://user-images.githubusercontent.com/20797432/33634817-f45d48aa-da2e-11e7-9a37-f6a51fe47a36.png">

found a solution, works for inv() but we need better solution
[https://stackoverflow.com/questions/47114737/overlapping-accesses-pointer](url)

**Comment by AlexanderTar** [comment]
I have fixed this issue and migrated to Swift 4
